#!/bin/bash
#
#    /etc/rc.d/init.d/ipfloaterd
#
# Starts IPFloater daemon
#
# chkconfig: 345 65 35
# description: Starts the IPFloater daemon
# processname: ipfloaterd

### BEGIN INIT INFO
# Provides: IPFloater
# Required-Start: $local_fs $network $remote_fs
# Required-Stop: $local_fs $network $remote_fs
# Default-Start:  2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: start and stop ipfloater
# Description: start and stop ipfloater
### END INIT INFO

APPLICATION=IPFloater
LOGFILE=/var/log/ipfloater/ipfloater.log
PIDFILE=/var/lib/ipfloater/ipfloater.pid
APP=ipfloaterdaemon
DAEMON=$(which $APP)

if [ "$DAEMON" == "" ]; then
    [ -e /usr/bin/$APP ] && DAEMON=/usr/bin/$APP
    [ -e /usr/local/bin/$APP ] && DAEMON=/usr/local/bin/$APP
    [ -e ./$APP ] && DAEMON=./$APP
fi

if [ "$DAEMON" == "" ]; then
    echo "could not find the $APP daemon"
    exit 1
fi

function status {
    if [ $1 == '-f' ]; then
        if [ ! -e "$2" ]; then
            echo "could not find the pid file $2... maybe it is not started?"
            return 0
        fi
        PID=$(cat $2 | head -n 1 | awk '{print $1}')
    else
        PID=$1
    fi
    
    CHECK=$(ps --pid "$PID")
    if [ $? == 0 ]; then
        echo $PID
        return 1
    else
        echo "process not found"
        return 0
    fi
}

function stop {
    PID=$(status -f $PIDFILE)
    if [ $? == 1 ]; then
        kill $PID
        if [ $? == 0 ]; then
            # echo "process killed... deleting pid file"
            rm -f $PIDFILE
            return 1
        else
            echo "could not kill the process ($PID)"
            return 0
        fi
        return 1
    else
        echo "could not find the IPFloater server ($PID)"
        return 0
    fi
}

function start {
    if [ -e "$PIDFILE" ]; then
        echo "pid file $PIDFILE exists... checking if $APP is running"
        PID=$(status -f $PIDFILE)
        if [ $? == 1 ]; then
            echo "$APP is already running"
            return 0
        else
            echo "assuming that $APP is not running"
            rm -f "$PIDFILE"
        fi
    fi
    
    DIRLOG=$(dirname "$LOGFILE")
    if [ "$DIRLOG" == "" ]; then
        LOGFILE=/var/log/ipfloater/ipfloater.log
        DIRLOG=/var/log/ipfloater
    fi

    [ ! -d "$DIRLOG" ] && mkdir -p "$DIRLOG"
    
    /usr/bin/python $DAEMON > /dev/null 2>> "$LOGFILE" &
    PID=$!
    sleep 2
    status $PID > /dev/null
    if [ $? == 1 ]; then
        DIRPID=$(dirname $PIDFILE)
        if [ ! -d "$DIRPID" ]; then
            mkdir -p "$DIRPID"
            [ $? -ne 0 ] && echo "could not create directory for pid file, check permissions for dir $DIRPID"
        fi
        echo $PID > $PIDFILE
        [ $? -ne 0 ] && echo "could not create pid file $PIDFILE, check permissions"
        return 1
    else
        return 0
    fi
}

function start_msg {
    RESULT=$(start)
    if [ $? == 1 ]; then
        echo "** $APPLICATION successfully started"
        return 0
    else
        echo "** error starting $APPLICATION. Please check logs or try launching daemon with the next command: \"/usr/bin/python $DAEMON\""
        echo "$RESULT"
        return 1
    fi
}

function stop_msg {
    RESULT=$(stop)
    if [ $? == 1 ]; then
        echo "** $APPLICATION stopped successfully"
        return 0
    else
        echo "** error stopping $APPLICATION. Please check logs"
        echo "$RESULT"
        return 1
    fi
}

case "$1" in
  start)
    start_msg
    exit $?
    ;;
  stop)
    stop_msg
    exit $?
    ;;
  restart)
    stop_msg
    [ $? == 0 ] && sleep 2 && start_msg
    exit $?
    ;;
  status)
    PID=$(status -f $PIDFILE)
    if [ $? == 1 ]; then
        echo "process running at pid $PID"
    else
        echo $PID
        exit 1
    fi
    ;;
  *)
    echo "Usage: $0 {start|stop|status}"
    exit 1
    ;;
esac

exit 0
